name: Build and Publish

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 1. Database Importer Image
      - name: Build and push db-import
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/docker/Dockerfile
          target: db-import
          push: true
          tags: ghcr.io/doxedon/ac-wotlk-db-import:master

      # 2. Worldserver Image
      - name: Build and push Worldserver
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/docker/Dockerfile
          target: worldserver
          push: true
          tags: ghcr.io/doxedon/ac-wotlk-worldserver:master

      # 3. Authserver Image
      - name: Build and push Authserver
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/docker/Dockerfile
          target: authserver
          push: true
          tags: ghcr.io/doxedon/ac-wotlk-authserver:master